server:
  port: 8082

spring:
  shardingsphere:
    datasource:
      names:
        master, slave1 ,slave2
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://124.223.103.8:3306/cloud_user?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: yangjin15@#*A
      slave1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://124.223.103.8:3307/cloud_user?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: yangjin15@#*A
      slave2:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://124.223.103.8:3308/cloud_user?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: yangjin15@#*A
    masterslave:
        # 读写分离配置 //轮寻
      load-balance-algorithm-type: round_robin
        # 最终的数据源名称
      name: dataSource
        # 主库数据源名称
      master-data-source-name: master
        # 从库数据源名称列表，多个逗号分隔
      slave-data-source-names: slave1, slave2
    props:
      sql:
        show: true #开启SQL显示，默认false
  main:
    allow-bean-definition-overriding: true


mybatis:
  type-aliases-package: org.yj.pojo
  configuration:
    map-underscore-to-camel-case: true



