server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3308/cloud_user?serverTimezone=UTC
    username: root
    password: 123456

mybatis:
  type-aliases-package: org.yj.pojo
  configuration:
    map-underscore-to-camel-case: true



