server:
  port: 8082

spring:
  shardingsphere:
    datasource:
      names:
        master,slave
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/cloud_user?serverTimezone=UTC
        username: root
        password: yangjin15@#*A
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3307/cloud_user?serverTimezone=UTC
        username: root
        password: yangjin15@#*A
    masterslave:
        # 读写分离配置 //轮寻
      load-balance-algorithm-type: round_robin
        # 最终的数据源名称
      name: dataSource
        # 主库数据源名称
      master-data-source-name: master
        # 从库数据源名称列表，多个逗号分隔
      slave-data-source-names: slave
    props:
      sql:
        show: true #开启SQL显示，默认false
  main:
    allow-bean-definition-overriding: true


mybatis:
  type-aliases-package: org.yj.pojo
  configuration:
    map-underscore-to-camel-case: true



