


spring:
  application:
    name: orderservice
  main:
    allow-bean-definition-overriding: true #当项目中有相同的类名时，直接覆盖
  profiles:
    active: @spring.profiles.active@
    include: @spring.profiles.active@DB ,@spring.profiles.active@Feign ,@spring.profiles.active@Nacos

mybatis:
  type-aliases-package: org.yj.pojo
  configuration:
    map-underscore-to-camel-case: true







