server:
  port: 8070

spring:
  application:
    name: gatewayservice
  cloud:
    nacos:
      server-addr: @nacos.addr@
      discovery:
        namespace: @nacos.namespace@ #发布服务实例的命名空间，
        cluster-name: chengdu #发布服务的集群实例名称（优先调用的集群服务实例）
    gateway:
      routes:
        - id: user-service # 路由标示，必须唯一
          uri: lb://userservice # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/user/** # 路径断言，判断路径是否是以/user开头，如果是则符合
          filters: #配置过滤器（过滤器很做很多事，）
            - AddRequestHeader=X-Request-red, blue-user
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/**
#            - After=   #通过在特定时间之后才能访问
          filters:
            - AddRequestHeader=X-Request-red, blue_order
      default-filters: #这里是配置所有的过滤器（上面的单独配置的过滤器依然有效，并且排在这个过滤器之后）
        - AddRequestHeader=X-Request-red, blue_all


logging:
  level:
    org.yj: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
