server:
  port: 8070

spring:
  application:
    name: gatewayservice
  cloud:
    nacos:
      server-addr: localhost:8840
      discovery:
        namespace: 84b49b39-b5d3-45e8-a161-45837b5fe323 #发布服务实例的命名空间，
        cluster-name: chengdu #发布服务的集群实例名称（优先调用的集群服务实例）
    gateway:
      routes:
        - id: user-service # 路由标示，必须唯一
          uri: lb://userservice # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/user/** # 路径断言，判断路径是否是以/user开头，如果是则符合
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/**


logging:
  level:
    org.yj: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
