server:
  port: 8081


spring:
  application:
    name: orderservice
  cloud:
    nacos:
      server-addr: localhost:80
      discovery:
        cluster-name: chengdu #设置集群名称
        namespace: 3b0a8c43-b94e-43a5-89b2-43ac17968344 #这里是设置服务注册的命名空间（不同的命名空间的服务不互通）
#        ephemeral: false #是否临时实例（默认true）。false时这个实例即使无法链接也不会成为无效服务（nacos2.1版本，集群模式会有注册不上服务的问题）
        username: nacos
        password: nacos
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/cloud_order?serverTimezone=UTC
    username: root
    password: 123456
#nacos和euraka的区别：nacos可以主动推送服务实例，nacos默认ap模式，和eureka一样，但是当实例中由非临时实例时，nacos转化成cp模式（高可靠）

#针对某个服务做负载均衡
userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule  # 负载均衡规则（这里是优先访问同集群实例，如果同集群挂了，那么就会访问其他的集群，并发出警告信息到控制台。）

ribbon:
  eager-load:
    enabled: true # 开启饥饿加载
    clients: # 指定饥饿加载的服务名称
      - userservice




mybatis:
  type-aliases-package: org.yj.pojo
  configuration:
    map-underscore-to-camel-case: true



